apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-hoxb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-6-tenant/load-app-836e6c1b-3fc2-466b-9898-3d924c4f5699/devfile-sample-python-basic-hoxb@sha256:790f561d183ecc3ce063334710007291298b0e6f6e41ed3cd5875df9008b1cb6
        name: my-python
        resources: {}
status: {}
